micronaut:
  application:
    name: dataStore
mongodb.uri: mongodb+srv://app:${PASSWORD}@cv-data-store.xqyxt.gcp.mongodb.net/cvdata?retryWrites=true&w=majority

app:
  mongoDb:
    databaseName: cvdata
    collectionName: cvdata
