micronaut:
  application:
    name: dataStore
mongodb.uri: mongodb://app:${PASSWORD}@cv-data-store-shard-00-00.xqyxt.gcp.mongodb.net:27017,cv-data-store-shard-00-01.xqyxt.gcp.mongodb.net:27017,cv-data-store-shard-00-02.xqyxt.gcp.mongodb.net:27017/cvdata?ssl=false&replicaSet=atlas-qbb41w-shard-0&authSource=admin&retryWrites=true&w=majority

app:
  mongoDb:
    databaseName: cvdata
    collectionName: cvdata
