micronaut:
  application:
    name: dataStore

mongodb:
  uri: mongodb+srv://app:${PASSWORD}@cv-data-store.xqyxt.gcp.mongodb.net/cvdata

app:
  mongoDb:
    databaseName: cvdata
    collectionName: cvdata
