name: Backend Service

on:
  push:
    branches: [ master ]
#    paths: 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew jibDockerBuild -x test

      - name: Setup env vars
        run: echo "PASSWORD=$MONGODB_PASSWORD" > VARS.env && cat VARS.env
        shell: bash
        env:
          MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}

      - name: Deploy
        uses: stefda/action-cloud-run@v1.0
        with:
          image: gcr.io/shanika-wijerathna/cv-data-store
          service: cv-data-store
          project: shanika-wijerathna
          region: us-central1
          env: ./VARS.env
          service key: ${{ secrets.GCLOUD_AUTH }}



