name: Fierbase Hosting

on:
  push:
    branches: [ master ]
    paths: 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build Frontend
        run: |
          yarn install
          yarn build

      - name: Deploy to Firebase
        uses: shanika/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: shanika-wijerathna
          SUB_DIR: frontend


